### ISSUE TITLE
Feature Request: Fixing links on Reddit and Twitter

### ISSUE THREAD

**Issue by kurobeats** [palant/searchlinkfix#65] opened 2018-05-07 21:17 UTC
The title says it all. Both networks provide the user with their own link. I believe twitter is t.co and reddit is redd.it

**Comment by palant** [comment] 2018-05-08 10:42
This is a duplicate of #50. In short: making this extension mess with websites that aren't search engines would be too confusing.

**Closed by palant** 2018-05-08 10:42 UTC
Labels: duplicate
