### ISSUE TITLE
Does not work in Firefox for Android

### ISSUE THREAD

**Issue by M-W99** [palant/searchlinkfix#56] opened 2017-12-14 17:19 UTC
Running the latest version of the addon on the latest Firefox on Android 7 (Samsung Galaxy S8). The addon installs without a hitch, but doesn't actually do anything. Links on Google search pages are not converted.

I'd be happy to provide any additional information that would help.
Thanks!

**Comment by palant** [comment] 2017-12-14 19:04
This is a duplicate of #34

**Closed by palant** 2017-12-14 19:04 UTC
Labels: duplicate
