### ISSUE TITLE
Google search results aren't parsed in mobile

### ISSUE THREAD

**Issue by Zcehtro** [palant/searchlinkfix#62] opened 2018-03-31 16:31 UTC
I just installed the add-on in Firefox for Android and the links aren't fixed.

I supposed that the problem was that it only worked in the desktop version. So I activated the "Request desktop site" option and voila: all the links were fixed correctly as expected.

Please make this add-on compatible with mobile sites. Thanks.

**Comment by palant** [comment] 2018-03-31 18:02
This is a duplicate of #34, listed under "known limitations."

**Closed by palant** 2018-03-31 18:02 UTC
Labels: duplicate
