### ISSUE TITLE
Workaround for mobiles

### ISSUE THREAD

**Issue by Marco-Sulla** [palant/searchlinkfix#81] opened 2019-07-16 09:10 UTC
> This extension cannot recover links after they have been modified. This means that it doesn’t work on Google Search on smartphones (tablet version will work fine) or if JavaScript is disabled — Google will produce modified links from the start rather than changing them when you click the link.

Well, the original links are inside `<cite>` tags...

**Comment by Marco-Sulla** [comment] 2019-07-16 09:17
Excuse me, not on mobile. But on mobile you can remove the leading "/url?q=" and all after "&amp;sa="

**Comment by palant** [comment] 2019-07-16 09:24
No, not on mobile. All you have on mobile is a `<span>` tag showing the URL - but it is a modified version of it.

> But on mobile you can remove the leading "/url?q=" and all after "&sa="

This approach is out of scope for this extension, see https://github.com/palant/searchlinkfix/issues/34#issuecomment-349253511

Closing as a duplicate of #34.

**Closed by palant** 2019-07-16 09:24 UTC
Labels: duplicate
