### ISSUE TITLE
Wikipedia bug on Android

### ISSUE THREAD

**Issue by GuyXY** [palant/searchlinkfix#38] opened 2017-03-27 08:32 UTC
Whenever I click on a Wikipedia link from Google on my Android device, nothing happens. The site just doesn't load.

**Comment by timofonic** [comment] 2017-07-23 00:41
Has this been fixed?

**Comment by palant** [comment] 2017-08-03 11:40
I don't know, but at least I cannot reproduce on the mobile version of Google.

**Comment by palant** [comment] 2017-08-03 12:53
Doesn't reproduce on Android either for me. I've got Firefox 54 and Google search link fix 1.6.3 on Android 6.0.1. I go to google.com, search for "test", then click the Wikipedia search result. For me it opens in the same tab just fine.

**Comment by palant** [comment] 2017-08-03 19:42
As we just just established in #40, Google Search is quite different depending on whether you use a smartphone or a tablet. I tried both now but couldn't reproduce this issue. I'm resolving this issue, let me know if you can still reproduce - I'll reopen then. Please provide additional details such as your Firefox and Android version, what device you are using and what you are searching for (meaning: what exact link you click on).

**Closed by palant** 2017-08-03 19:42 UTC
Labels: worksforme
