### ISSUE TITLE
add support for baidu.com?

### ISSUE THREAD

**Issue by wi24rd** [palant/searchlinkfix#82] opened 2019-07-24 06:18 UTC
When searching in www.baidu.com, it returns link begined with 'http://www.baidu.com/link?url='.

Check http://zh.wikipedia.org/wiki/对百度的争议

And its CEO Robin Li said, 'Chinese are glad to gain convenient by losing their privacy in many case' 

https://tech.qq.com/a/20180326/025802.htm

But the truth is there are so many people who care about it.
I think this extension can help them.

**Comment by palant** [comment] 2019-07-24 06:22
This is a duplicate of #74.

**Closed by palant** 2019-07-24 06:22 UTC
Labels: duplicate

**Comment by wi24rd** [comment] 2019-07-24 06:25
what about so.com and sogou.com?

**Comment by palant** [comment] 2019-07-24 06:37
It's the same thing there, sorry.
