### ISSUE TITLE
Doesn't work with FF 57 mobile and Google

### ISSUE THREAD

**Issue by motatuc** [palant/searchlinkfix#53] opened 2017-11-17 13:49 UTC
Hello,

Thanks for your great addon - works like it is supposed to do with FF 57 on PC.
But unfortunately it does not work with FF 57 mobile and Google links. They are still tainted.

Could you have a look into that?

Thanks

**Comment by palant** [comment] 2017-11-29 12:54
This is a duplicate of #34.

**Closed by palant** 2017-11-29 12:54 UTC
Labels: duplicate
