### ISSUE TITLE
doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by jawz101** [palant/searchlinkfix#40] opened 2017-05-22 21:59 UTC
I still get google strings when copying links to the clipboard.

Don't Track Me Google does work
https://github.com/Rob--W/dont-track-me-google

**Comment by Madrugada** [comment] 2017-07-04 03:49
Same here.  Oneplus 3T.Android 7.1.1.

**Comment by timofonic** [comment] 2017-07-22 23:44
Any hopes for fix?

**Comment by palant** [comment] 2017-07-23 08:19
Yes, once I manage to test this in an emulator. Definitely not in the next week however.

**Comment by palant** [comment] 2017-08-03 12:49
Doesn't quite reproduce for me. I've got Firefox 54 and Google search link fix 1.6.3 on Android 6.0.1. I go to google.com, search for "test" and tap & hold on the Wikipedia search result. Copy the URL via appearing context menu, then paste it into the location bar - I get https://de.wikipedia.org/wiki/Test. Clicking the links seems to work fine as well. Are you doing something different?

**Comment by Madrugada** [comment] 2017-08-03 13:59
>> Are you doing something different?

 

Not really.

 

https://youtu.be/3s8MNytDGrg

 

Android 7 is about the only difference based on your description.

 

I can do some other testing, but as another poster pointed out Don't Track Me Google does work so there isn’t a big incentive.

**Comment by EchoDev** [comment] 2017-08-03 15:28
I can confirm it doesn't work for me either on Android 7 with latest Firefox
Copying the URL still gives the Google tracking URL.

This one actually does work: https://addons.mozilla.org/en-us/firefox/addon/google-search-link-fix-for-/ 

Maybe it is possible to figure out what the above addon is doing differently from this one?

**Comment by palant** [comment] 2017-08-03 19:31
Ok, it seems that the issue is only with the version of Google Search delivered to phones, not tablets. And my bad for not remembering, this is actually a duplicate of #34.

**Closed by palant** 2017-08-03 19:31 UTC
Labels: duplicate
