### ISSUE TITLE
Not working for Google in the Android version of Firefox

### ISSUE THREAD

**Issue by GuyXY** [palant/searchlinkfix#61] opened 2018-03-19 21:46 UTC
This add-on doesn't seem to work for Google in the Android version of Firefox. What I mean by that is that when you copy a link in the Google search results, you don't get the link you were actually expecting to get but a link that redirects you through Google first. The link that you get will look like this: `https://www.google.[tld]/url?q=[wanted_url]&[other_(tracker?)_information]`
Knowing this, I'm also kind of skeptic, if the add-on even works when you simply click on the link without copying it, or if the exact same thing is going to happen.

**Comment by palant** [comment] 2018-03-20 06:35
This is a duplicate of #34, actually listed under known limitations.

**Closed by palant** 2018-03-20 06:35 UTC
Labels: duplicate
