### ISSUE TITLE
show complete target url

### ISSUE THREAD

**Issue by hpvd** [palant/searchlinkfix#27] opened 2016-01-11 16:03 UTC
this extension is perfectly working. Many thanks to all contributors!

When already "fixing" a link, it would be very handy to directly show this full link instead of the shortened one.
The reason:
the full path of the link often contains great informations to decide if  something is worth to follow or not.
e.g.: if you are looking for new information on a topic and you identify the path includes the year 2012 you may skip this result.
=> This would save tons of time...
(since one do not have to look to bottom of the browser where the link target is shown)

please see attachments

and btw: **this is also some kind of fixing the searchlinks :-)**

=> what do you think?

![2016-01-11_17h10_06](https://cloud.githubusercontent.com/assets/5681880/12239373/ba431d44-b888-11e5-8c3d-944996dc7583.png)

![2016-01-11_17h13_41](https://cloud.githubusercontent.com/assets/5681880/12239407/df70f168-b888-11e5-8bcd-6417833422d9.png)

**Comment by palant** [comment] 2016-01-12 12:36
There are several issues with that suggestion:

* What Google shows there isn't always a link, often it displays the page's position in the site's hierarchy (e.g. "addons.mozilla.org › Add-ons for Firefox › Extensions"). That hierarchy is also shortened occasionally.
* Nor is replacing a shortened link by a longer version all that trivial because search keywords can be marked up within the link - that markup somehow has to be reproduced then.
* Even if the extension did this, it resulting layout would be pretty ugly. Google's search results have a fixed width (namely 42em which corresponds to 512 pixels for me), overly long links won't look nice there.
* Finally, it's not like Google makes changing their websites easy. The class names used are semi-random and change regularly. I would have to adjust the extension regularly because Google changed something once again.

In fact, the best solution would be a tooltip that displays the link target - for all links, not just Google. I searched an this extensions apparently [already exists](https://addons.mozilla.org/addon/url-tooltip/). As to Google search link fix: sorry, out of scope.

**Closed by palant** 2016-01-12 12:36 UTC

**Comment by hpvd** [comment] 2016-01-12 12:46
many thanks for your detailed answer!!
and especially for pointing to the tooltip extension.
When trying it I found it seems not to be compatible
![2016-01-12_13h43_35](https://cloud.githubusercontent.com/assets/5681880/12263870/d4f5865e-b932-11e5-9032-0a214803356b.png)
