### ISSUE TITLE
Add support for Reddit?

### ISSUE THREAD

**Issue by CapacitorSet** [palant/searchlinkfix#57] opened 2017-12-20 23:54 UTC
Reddit implements a similar feature, redirecting outbound links through out.reddit.com for tracking purposes. Although this can be disabled from one's profile, it still works when logged out, and in general it would be nice if this extension also covered Reddit.

As it stands now, it suffices to remove all data- attributes beginning with `data-outbound-`. For instance, this is the original post:

```html
<a
    class="title may-blank outbound"
    data-event-action="title"
    href="http://nymag.com/[...]"
    tabindex="1"
    data-href-url="http://nymag.com/[...]"
    data-outbound-url="https://out.reddit.com/t3_7l2xcu?url=http%3A%2F%2Fnymag.com%2F[...]&amp;token=AQAAeQU7WvulGNuqjbyUDg6DxCbH-RQtoKY8bUcsG82hno-u152b&amp;app_name=reddit.com"
    data-outbound-expiration="1513817465000"
    rel="">Wall Street Journal Killed Editorial on Trump’s Mob Ties</a>
```

and it should be replaced with this:

```html
<a
    class="title may-blank outbound"
    data-event-action="title"
    href="http://nymag.com/[...]"
    tabindex="1"
    data-href-url="http://nymag.com/[...]"
    rel="">Wall Street Journal Killed Editorial on Trump’s Mob Ties</a>
```

**Comment by palant** [comment] 2017-12-21 09:21
This is a duplicate of #50.

**Closed by palant** 2017-12-21 09:21 UTC
Labels: duplicate
